### ISSUE TITLE
Why the master branch has an outdated code?

### ISSUE THREAD

**Issue by anyt** [marellocommerce/marello-application#13]
It's a bit confusing that the master branch is based on oro/platform:3.1, but the latest version is 3.0.
I would expect the master to be in sync or ahead of 3.0, or if the branch is abandoned, you can just remove it and make 3.0 the default one.

**Comment by 24198** [comment]
Hi @anyt,

Thanks for reporting. You are right, we have been a little behind in updating the master branch. We might need to consider on wether this is still (for us) the way to handle this, but we will update it soon.


Jaimy
