### ISSUE TITLE
login error 

### ISSUE THREAD

**Issue by soitun** [marellocommerce/marello-application#7]
Hello, I have installed marello, thank you very much for the work of the marello team.
However, I have encountered a new problem now, and I have not been able to log in to the system by entering the correct username and password.
My nginx configuration is as follows:

`
server {
    listen 80;
    server_name erp.myzlink.com;
    root /home/htdocs/marello-application/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~* ^[^(\.php)]+\.(jpg|jpeg|gif|png|ico|css|txt|bmp|js)$ {
        add_header Cache-Control public;
        expires 1h;
        access_log off;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        include                         fastcgi_params;
        fastcgi_pass                    phpbackend;
        fastcgi_index                   index.php;
        fastcgi_buffer_size             128k;
        fastcgi_buffers                 64   64k;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS            off;
    }
}`

**Comment by 24198** [comment]
Hi @soitun,

By the looks of it, the ‘var/sessions’ directory doesn’t have sufficient permissions to write. Could you please verify that the directory has sufficient permissions?

Kind Regards,


Jaimy Casteleijn

**Comment by soitun** [comment]
Thank you for your reply, I will check it right away.

**Comment by soitun** [comment]
Solved, thank you very much
