### ISSUE TITLE
product image can not display

### ISSUE THREAD

**Issue by soitun** [marellocommerce/marello-application#8]
hi,  Product image can not display.

**Comment by 24198** [comment]
Hi @soitun,

Thank you for reporting, can you be a little more specific in regards to your setup and steps to reproduce the issue?


Kind Regards,


Jaimy Casteleijn

**Comment by soitun** [comment]
hi @24198  thank you for reply quickly . 
product image src 
/media/cache/attachment/resize/840/product_grid/5d49a95f95577299995203

**Comment by 24198** [comment]
Hi @soitun,

Could you please provide:
- The Marello version you are using
- The Marello edition you are using
- The steps to reproduce this issue, what did you do in order to come across the problem you're reporting.

Thanks!

Jaimy

**Comment by soitun** [comment]
Marello version : 2.1.0  Community
I installed it according to the following steps. The image of the product after installation can not be displayed correctly.
1.  git clone -b 2.1.0 https://github.com/marellocommerce/marello-application.git
2. cd marello-application 
3. composer install --prefer-dist --no-dev
4. php bin/console oro:install --env prod 
5. php bin/console gos:websocket:server --env prod & 
6. php bin/console oro:cron --env prod &
7. php bin/console oro:message-queue:consume --env=prod

After installation, all seems to work fine, but the product image can not be displayed

**Comment by 24198** [comment]
Hi @soitun,

Thank you for the information, we'll try and see if we are able to reproduce the results.

Kind Regards,

Jaimy

**Comment by soitun** [comment]
@24198  thank you again.

**Comment by 24198** [comment]
Hi @soitun,

We have been trying to reproduce the issue, but we were not successful in doing so. We have installed a clean version of Marello 2.1.0 CE and are able to upload the images, see them on the product grid and view. 

One of the possible issues we can think of, is that it might have to do with permissions on some of the directories from which the image is being fetched. 
Could you please verify that permissions for the `var/attachment` and `public/media` have sufficient permissions to fetch the images?

Another thing you could try, is uploading a new image for a product and see whether this is being displayed correctly (on the view and product grid). 


Kind Regards,


Jaimy
